/* This file was generated by awk's script */
/* cv-tab.awk : *.csv -> *_tab.h */
/* rcv-tab.awk: *.csv <- *_tab.h */
	{
		NULL, N_MSG_ITEM_UNKNOWN, COIN_KIND_NULL,
		FACE_MNR_NULL,
		(rate_t)0, 0,
	},
	{
		NULL, N_MSG_COIN_GOLD, COIN_KIND_GOLD,
		FACE_MNR_NULL,
		(rate_t)80, 100,
	},
	{
		NULL, N_MSG_COIN_SILVER, COIN_KIND_SILVER,
		FACE_MNR_NULL,
		(rate_t)0, 10,
	},
	{
		NULL, N_MSG_COIN_COPPER, COIN_KIND_COPPER,
		FACE_MNR_NULL,
		(rate_t)0, 1,
	},
	{
		NULL, N_MSG_NULL, COIN_KIND_NULL,
		FACE_MNR_NULL,
		(rate_t)0, 0,
	},
