/* This file was generated by awk's script */
/* cv-tab.awk : *.csv -> *_tab.h */
/* rcv-tab.awk: *.csv <- *_tab.h */
	{
		NULL, N_MSG_ITEM_UNKNOWN,
		ANTHOLOGY_KIND_NULL,
	},
	{
		NULL, N_MSG_ANTHOLOGY_CURE,
		ANTHOLOGY_KIND_CURE,
	},
	{
		NULL, N_MSG_ANTHOLOGY_STRENGTHEN_ABL,
		ANTHOLOGY_KIND_STRENGTHEN_ABL,
	},
	{
		NULL, N_MSG_ANTHOLOGY_WEAKEN_ABL,
		ANTHOLOGY_KIND_WEAKEN_ABL,
	},
	{
		NULL, N_MSG_ANTHOLOGY_RESI_STAT,
		ANTHOLOGY_KIND_RESI_STAT,
	},
	{
		NULL, N_MSG_NULL,
		ANTHOLOGY_KIND_NULL,
	},
