/* This file was generated by awk's script */
/* cv-tab.awk : *.csv -> *_tab.h */
/* rcv-tab.awk: *.csv <- *_tab.h */
	{
		NULL, N_MSG_ITEM_UNKNOWN,
		PIPE_KIND_NULL,
		(rate_t)0, 0, 0,
		TOBACCO_KIND_NULL,
		0, FLG_NULL,
	},
	{
		NULL, N_MSG_PIPE_PIPE,
		PIPE_KIND_PIPE,
		(rate_t)80, 1, 365,
		TOBACCO_KIND_CUT_TOBACCO,
		500, FLG_NULL,
	},
	{
		NULL, N_MSG_PIPE_KISEL,
		PIPE_KIND_KISEL,
		(rate_t)80, 1, 365,
		TOBACCO_KIND_CUT_TOBACCO,
		600, FLG_NULL,
	},
	{
		NULL, N_MSG_PIPE_CIGARET_HOLDER,
		PIPE_KIND_CIGARET_HOLDER,
		(rate_t)80, 20, (4 * 5 * TURN_PER_MINUTE),
		TOBACCO_KIND_CIGARET,
		2, FLG_PIPE_CONSUMPTION,
	},
	{
		NULL, N_MSG_NULL,
		PIPE_KIND_NULL,
		(rate_t)0, 0, 0,
		TOBACCO_KIND_NULL,
		0, FLG_NULL,
	},
