/***************************************************************
* L&L - Labyrinths & Legends
* Copyright (c) 1993-2014 YOSHIMURA Tomohiko All rights reserved.
* 
* Created by BowKenKen
*   URL: https://sourceforge.jp/projects/lnl/
* 
* License is GPL
* 
* 本プログラムはフリー・ソフトウェアです。
* あなたは、 Free Software Foundation が公表した
*  GNU 一般公有使用許諾の「バージョン２」
* 或はそれ以降の各バージョンの中からいずれかを選択し、
* そのバージョンが定める条項に従って本プログラムを
* 再頒布または変更することができます。
* 
* 本プログラムは有用とは思いますが、頒布にあたっては、
* 市場性及び特定目的適合性についての暗黙の保証を含めて,
* いかなる保証も行ないません。
* 詳細については GNU 一般公有使用許諾書をお読みください。
* 
* あなたは、本プログラムと一緒に GNU 一般公有使用許諾書
* の写しを受け取っているはずです。そうでない場合は、
*   Free Software Foundation, Inc.,
*   59 Temple Place, Suite 330, Boston, MA 02111-1307, USA
* へ手紙を書いてください。
* 
* $Id: sound-kind.h,v 1.9 2014/01/07 23:40:42 bowkenken Exp $
***************************************************************/

#ifndef	SOUND_KIND_KIND_H
#define	SOUND_KIND_KIND_H

/* SE (Sound Effect) の種類 */

typedef enum {
	SOUND_KIND_NULL,

	SOUND_KIND_TRAP_SAFE,
	SOUND_KIND_TRAP_DISARM,
	SOUND_KIND_TRAP_CAUGHT,

	SOUND_KIND_SPELL_SOR,
	SOUND_KIND_SPELL_ENC,
	SOUND_KIND_SPELL_NIN,
	SOUND_KIND_SPELL_BAR,
	SOUND_KIND_SPELL_MAG,
	SOUND_KIND_SPELL_SUM,
	SOUND_KIND_SPELL_SHA,
	SOUND_KIND_SPELL_PRI,

	SOUND_KIND_BLAST_MEMBER,
	SOUND_KIND_BLAST_MONSTER,
	SOUND_KIND_BLAST_DESTRUCTION,

	SOUND_KIND_MENU_CANCEL,
	SOUND_KIND_MENU_SELECT,

	SOUND_KIND_FIGHT_DIE_MEMBER,
	SOUND_KIND_FIGHT_DIE_MONSTER_BOSS_LAST,
	SOUND_KIND_FIGHT_DIE_MONSTER_BOSS,
	SOUND_KIND_FIGHT_DIE_MONSTER,
	SOUND_KIND_FIGHT_DEFENSE_MISS_MEMBER,
	SOUND_KIND_FIGHT_DEFENSE_MISS_MONSTER_BOSS_LAST,
	SOUND_KIND_FIGHT_DEFENSE_MISS_MONSTER,
	SOUND_KIND_FIGHT_DEFENSE_HIT_MEMBER,
	SOUND_KIND_FIGHT_DEFENSE_HIT_MONSTER,
	SOUND_KIND_FIGHT_DEFENSE_CRITICAL_MEMBER,
	SOUND_KIND_FIGHT_DEFENSE_CRITICAL_MONSTER,
	SOUND_KIND_FIGHT_FIND_MEMBER,
	SOUND_KIND_FIGHT_FIND_MONSTER_BOSS,
	SOUND_KIND_FIGHT_FIND_MONSTER,
	SOUND_KIND_FIGHT_ATTACK_LAST_BOSS_ATTACK,
	SOUND_KIND_FIGHT_ATTACK_LAST_BOSS_WEAKEN,
	SOUND_KIND_FIGHT_ATTACK_LAST_BOSS_SLAP,
	SOUND_KIND_FIGHT_ATTACK_THROW_MEMBER,
	SOUND_KIND_FIGHT_ATTACK_THROW_MONSTER,

	SOUND_KIND_REQUEST_FINISH,

	SOUND_KIND_SHOP_SALE,
	SOUND_KIND_SHOP_BUY_DRINK,
	SOUND_KIND_SHOP_BUY,

	SOUND_KIND_EVENT_GATE,
	SOUND_KIND_EVENT_DRIVE,
	SOUND_KIND_EVENT_EARTHQUAKE,

	SOUND_KIND_LEVEL_DOWN,
	SOUND_KIND_LEVEL_UP,

	SOUND_KIND_DOOR_CLOSE,
	SOUND_KIND_DOOR_OPEN,

	SOUND_KIND_STAIRS_DOWN,
	SOUND_KIND_STAIRS_UP,

	SOUND_KIND_ITEM_USE,
	SOUND_KIND_ITEM_OPEN,
	SOUND_KIND_ITEM_SMOKE,

	SOUND_KIND_ACTION_APPEAR,
	SOUND_KIND_ACTION_TELEPORT_RECALL,
	SOUND_KIND_ACTION_TELEPORT_PARTY,
	SOUND_KIND_ACTION_TELEPORT_SHORT,
	SOUND_KIND_ACTION_TELEPORT_LONG,

	SOUND_KIND_MAX_N,
} sound_kind_t;

#endif	/* SOUND_KIND_KIND_H */
